### ISSUE TITLE
Consider removing dependency from anyscalar

### ISSUE THREAD

**Issue by nodkz** [ikari-pl/graphql-compose-leveler#1]
Nice package! 👍

You may use graphql-compose built-in type 'JSON' for any value (not just scalars):
https://github.com/ikari-pl/graphql-compose-leveler/blob/fe8326f1dce668a0eb0a4f383f79c3bf6e5d46f9/lib.js#L21

```js
addFields({
  field: 'JSON',
});
```

**Comment by ikari-pl** [comment]
Let's say noticing this is better late than never. Thanks! :)
I'll gladly drop the dependency, one less thing to worry about.
